language: generic
sudo: required
cache: false
install: skip
matrix:
  fast_finish: true
services:
  - docker
git:
  depth: false
branches:
  only:
  - master
if: (commit_message =~ ^daily OR type = "cron") AND (branch = master)
env:
  - WEBGRAB_FILENAME=configs/ar_arab.xml
script:
- git clone https://${GITHUB_API_TOKEN}@github.com/fazzani/grab.git > /dev/null 2>&1
- cd grab
- docker run -it --rm -v "${PWD}/${WEBGRAB_FILENAME}:/config/WebGrab++.config.xml" -v "${PWD}:/data" -e "DEBUG=false" synker/webgraboneshot:latest
- git add --all && (git commit -m "Webgrab ${WEBGRAB_FILENAME} from grab2" || echo "No changes to commit")
- (git pull && git push ) || (sleep 100 && git pull && git push)