language: generic
sudo: required
install: skip
cache: false
matrix:
  fast_finish: true
services:
  - docker
git:
  depth: false
branches:
  only:
  - master
if: (commit_message =~ ^daily OR type = "cron") AND (branch = master)
env:
  - WEBGRAB_FILENAME=configs/ar_el_cinema.xml
  - WEBGRAB_FILENAME=configs/ar_arab.xml
script:
- docker run -it --rm -v "${PWD}/${WEBGRAB_FILENAME}:/config/WebGrab++.config.xml" -v "${PWD}:/data" synker/webgraboneshot:latest
- git pull https://${GITHUB_API_TOKEN}@github.com/fazzani/grab.git > /dev/null 2>&1
- cp ./out/*.xmltv ./grab/out && cd grab
- git add --all && (git commit -m "Webgrab ${WEBGRAB_FILENAME} from grab2" || echo "No changes to commit")
- (git pull origin HEAD:master && git push origin HEAD:master) || (sleep 100 && git pull origin HEAD:master && git push origin HEAD:master)

jobs:
  include:
  - stage: merging
    name: Merging xmltv files
    script:
    - chmod +x docker/merge.sh
    - docker pull synker/xmltv_merge:latest
    - git pull https://${GITHUB_API_TOKEN}@github.com/fazzani/grab.git > /dev/null 2>&1 && cd grab
    - docker run -it -v "${PWD}:/work" -e GITHUB_API_TOKEN=${GITHUB_API_TOKEN} synker/xmltv_merge:0.0.3 /bin/bash -c "dos2unix docker/merge.sh && chmod +x docker/merge.sh && apt-get install zip -y && docker/merge.sh '*.xmltv'"
    - git add merge.tar.gz && git add merge.zip && git commit -m "compression and mergin xmltv files and pushing them to GITHUB. Triggred by $TRAVIS_EVENT_TYPE"
    - git pull && git push -u origin master
  - stage: Update readme
    name: Update readme
    before_script:
      - sudo apt-get update -qq
      - sudo apt-get install libxml2-utils xmlstarlet -y
      - npm install -g xml2json-cli
    script:
      - git pull https://${GITHUB_API_TOKEN}@github.com/fazzani/grab.git > /dev/null 2>&1 && cd grab
      - chmod +x ./scripts/*.sh
      - ./scripts/check_channels.sh *.xmltv ${TRAVIS_BUILD_NUMBER}
      - curl -s -H "Content-Type:application/json" -XPOST elastic.synker.ovh/missingepgchannels/report -d @./out/check_missing_programs.json
      - ./scripts/update_missed_channels.sh ./out/check_channels.json ./out/check_missing_programs.json

notifications:
  email:
    recipients:
      - tunisienheni@gmail.com
    on_success: change
    on_failure: change
